33: Fixes and comments for udsr dm create
wavelet-lab/usdr-lib pull request #34
Opened 2024-08-14 15:27 UTC by vd2org

2024-08-14 16:19 UTC, irodushka commented on src/tools/usdr_dm_create.c
> +#define DMCR "DMCR"
лучше LOG_TAG

2024-08-14 16:21 UTC, irodushka commented on src/tools/usdr_dm_create.c
> +    uint64_t temp[2];
а зачем тут массив?.. В usdr_dm_sensors вроде как просто uint64_t

2024-08-14 16:21 UTC, irodushka commented on src/tools/usdr_dm_create.c
> +        USDR_LOG(DMCR, USDR_LOG_ERROR, "Unable to get device temperature: errno %d", res);
better use USDR_LOG_WARNING for minor cases

2024-08-14 16:22 UTC, vd2org commented on src/tools/usdr_dm_create.c
> +#define DMCR "DMCR"
✅

2024-08-14 16:23 UTC, vd2org commented on src/tools/usdr_dm_create.c
> +        USDR_LOG(DMCR, USDR_LOG_ERROR, "Unable to get device temperature: errno %d", res);
✅

2024-08-16 23:06 UTC, dtv-comp requested changes

2024-08-16 23:06 UTC, dtv-comp commented on src/tools/usdr_dm_create.c
> +                USDR_LOG(LOG_TAG, USDR_LOG_ERROR, "Can't read %d bytes! res=%zd ferror=%d", s_rx_blksz, res, ferror(s_in_file[i]));
It should be `s_tx_blksz` instead `s_rx_blksz`

2024-08-16 23:06 UTC, dtv-comp commented on src/tools/usdr_dm_create.c
> +    USDR_LOG(LOG_TAG, severity, "Usage: %s '[-D device] [-f RX_filename] [-I TX_filename] [-c count] [-r samplerate] [-F format] [-C chmsk] [-S samples_per_blk] [-l loglevel] "
not all parameters are listed

2024-08-16 23:06 UTC, dtv-comp commented on src/tools/usdr_dm_create.c
> +    unsigned dotx = 0; //means "do TX"
It would be better: `TX flag, enables TX if equal to 1`

2024-08-16 23:06 UTC, dtv-comp commented on src/tools/usdr_dm_create.c
> +    unsigned dorx = 1; //means "do RX"
It would be better: RX flag, enables RX if equal to 1

2024-08-16 23:06 UTC, dtv-comp commented on src/tools/usdr_dm_create.c
> +        //Set file name to read TX data (will emit sine if omited)
I think, it would be better `...will transmit sine...` instead `...will emit sine...

2024-08-16 23:06 UTC, dtv-comp commented on src/tools/usdr_dm_create.c
> +        case 'h':
//Show usage

2024-08-16 23:06 UTC, dtv-comp commented on src/tools/usdr_dm_create.c
> +        USDR_LOG(LOG_TAG, USDR_LOG_INFO, "Defaulting devices to 1");
What does this message mean?

2024-08-16 23:06 UTC, dtv-comp commented on src/tools/usdr_dm_create.c
> +            USDR_LOG(LOG_TAG, USDR_LOG_ERROR, "Unable to start data stream: errno %d", res);
It should to specify the stream direction, as example `Unable to start RX data stream`

2024-08-16 23:06 UTC, dtv-comp commented on src/tools/usdr_dm_create.c
> +            USDR_LOG(LOG_TAG, USDR_LOG_ERROR, "Unable to start data stream: errno %d", res);
It should to specify the stream direction, as example `Unable to start TX data stream`

2024-08-16 23:06 UTC, dtv-comp commented on src/tools/usdr_dm_create.c
> +        USDR_LOG(LOG_TAG, USDR_LOG_ERROR, "Unable to set antcfg: errno %d", res);
It would be better if we will describe the `antcfg`

2024-08-16 23:06 UTC, dtv-comp commented on src/tools/usdr_dm_create.c
> +            USDR_LOG(LOG_TAG, USDR_LOG_ERROR, "Unable to stop data stream: errno %d", res);
It should to specify the stream direction, as example `Unable to stop TX data stream`

2024-08-16 23:06 UTC, dtv-comp commented on src/tools/usdr_dm_create.c
> +            USDR_LOG(LOG_TAG, USDR_LOG_ERROR, "Unable to stop data stream: errno %d", res);
It should to specify the stream direction, as example `Unable to stop RX data stream`

2024-08-16 23:31 UTC, irodushka commented on src/tools/usdr_dm_create.c
> +        USDR_LOG(LOG_TAG, USDR_LOG_INFO, "Defaulting devices to 1");
Who knows, it's @sergforce legacy)

2024-08-19 13:41 UTC, merged